# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'IntelliSearch.csproj'
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Docker@2
  inputs:
    command: 'login'
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/docker/Dockerfile'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
